server:
  port: 80
spring:
  application:
    name: provider-server
  datasource:
    username: gtwg
    password: Gwhl@testdb2020
    url: jdbc:mariadb://192.168.204.20:30582/gtwg?useUnicode=true&&characterEncoding=utf-8&&useSSL=false&&autoReconnect=true
    driver-class-name: org.mariadb.jdbc.Driver
#  mvc:
#    static-path-pattern: /static/**
#    view:
#      prefix: /templates/
#      suffix: .html
#  thymeleaf:
#    #缓冲的配置
#    cache: false
#    check-template: true
#    check-template-location: true
#    #开启MVC thymeleaf 视图解析
#    enabled: true
#    encoding: utf-8
#    mode: HTML
#    prefix: classpath:/templates/
#    suffix: .html
#  web:
#    resources:
#      static-locations: classpath:/static/



eureka:
  client:
    #此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetch-registry: false
    #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true,即自己注册自己。
    register-with-eureka: true
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      defaultZone: http://localhost:9090/eureka
  #服务注册中心实例的主机名
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: 127.0.0.1:80


